// import { multiply } from "./utility.js"; 
// const result=multiply(5,4,2);
// console.log(result);
// import *as utility from "./utility.js";
// const res=utility.mul(3,5,6);
// console.log(res);
//  import addition from "./utility";
import add from "./utility.js";
const result=add(5,4,2);
console.log(result);